# Global/default configuration
dist: xenial
language: php
sudo: false
services:
  - mysql
cache:
  npm: true
  directories:
    - $HOME/.composer/cache
    - build/node_modules
notifications:
  email: false

# Job list
matrix:
  fast_finish: true
  allow_failures:
    - name: Test with PHP nightly
    - name: Check PHP coding style
  include:

    - name: Test with PHP 7.2 (with code coverage)
      php: '7.2'
      before_script:
        - wget --tries=5 https://scrutinizer-ci.com/ocular.phar
        - ./.travis/composer-deps.sh
      script:
        - phpdbg -qrr ./concrete/vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover
      after_script:
        - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

    - name: Check PHP coding style
      php: '7.2'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - ./.travis/check-php-coding-style.sh

    - name: Rebuild JS assets
      language: node_js
      node_js: '10'
      before_script:
        - ./.travis/setup-build.sh
      script:
        - ./.travis/rebuild-assets.sh

    - name: Test with PHP 7.2
      php: '7.2'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test with PHP 7.3
      php: '7.3'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test with PHP 7.4
      php: '7.4'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test in Docker
      php: '7.2'
      services:
        - docker
        - mysql
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test -- --group docker

    - name: Test with PHP nightly
      php: nightly
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test
